version: "3.8"

services:
  db:
    image: postgres:15
    container_name: chat_app_db
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: Example
      POSTGRES_PASSWORD: Example

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data

volumes:
  db_data:
